### ISSUE TITLE
Salesforce disabling TLS 1.0

### ISSUE THREAD

**Issue by zacharycarter** [palominolabs/sf-api-connector#10]
Salesforce will soon be disabling TLS 1.0 - https://help.salesforce.com/apex/HTViewSolution?id=000221207#CRUCSetting

I'm currently using this app in a production scenario and I'm not exactly sure what changes / if any need to be made to comply. Our existing integration is failing when TLS 1.0 is disabled in our org. Any help would be greatly appreciated!

**Comment by marshallpierce** [comment]
It's possible that there are code changes needed, but the most likely suspect is an old JDK. Are you using Java 8?

**Comment by zacharycarter** [comment]
I am using 1.8 on my local machine where I'm testing from. Could it be because the project targeted 1.6? I can try rebuilding the project to target 1.8 and seeing if that doesn't solve the problem.

**Comment by marshallpierce** [comment]
Rebuilding shouldn't be necessary. To make sure we're looking in the right place, try capturing the TLS traffic in Wireshark and take a look at the outbound packets to make sure they're advertising TLS 1.1 or 1.2 in the ClientHello.

**Comment by zacharycarter** [comment]
Thanks for the help Marshall - I could have sworn I was running the project on Java 1.8 but I just verified I was indeed using 1.7 and didn't have the security settings on the JVM set to use TLS 1.1/1.2

I switched the project to use 1.8 and ran a wireshark session and the TLS protocol was set to 1.2 for the handshake. I think I'm good to go! Thanks again!

**Comment by marshallpierce** [comment]
No problem; glad the library is useful.
